name: build

on: [push]

jobs:

  build-and-test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: ghcr-login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: docker-push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ github.repository_owner }}/paas-grafana-annotation-resource:${{ github.sha }}
            ${{ github.repository_owner }}/paas-grafana-annotation-resource:${{ github.ref }}
